id: P07C4E480
initial_creation_type: input
source_metadata:
  title: Peaceful and Wrathful Deities
  language: bo
  description: 'Texts related to the forty-two peaceful and fifty-eight wrathful deities,
    known collectively as the zhitro (zhi khro):'
  volume:
    410fc3229edd48ff947dbfdc3159adfe:
      title: In Praise of the Meaning of the Main Mantras of the Peaceful and Wrathful
        Deities
      parent: Mantra
    a4e606efcaca4dc1ad6089527b19a547:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Sādhanas
created_at: '2022-03-01T05:03:07.343908'
last_modified_at: '2022-03-01T05:03:07.343910'
